### ISSUE TITLE
When setting config and options causes infinite render loop

### ISSUE THREAD

**Issue by londonbarrett** [Turanchoks/use-axios-request#6]
When I set config and options, the component is causing an infinite render loop.

**Comment by KateKate** [comment]
Could you please show your code? Thanks!

**Comment by londonbarrett** [comment]
Of course,

`
const { data, update } = useAxiosRequest({
    url: 'http://localhost:4000',
    params: {
      family: '342',
    },
  },
  {
    pollInterval: 0,
  });`

I am setting the pollInterval option because for some reason it is causing the infinite loop, I think the issue is related to that setting.

**Comment by KateKate** [comment]
You create a new object for every render and useAxiosRequest send a new request since it got a new object (config). You have two options:
1) carry out your config in constant out of a component
```
const CONFIG = {
    url: 'http://localhost:4000',
    params: {
      family: '342',
    },
  };
const YourComponent = () => {
  const { data, update } = useAxiosRequest(CONFIG);
}
```
2) memoize config if it depends on the props
```
const MyComponent = ({ family }) => {
  const config = React.useMemo(() => ({
      url: 'http://localhost:4000',
      params: {
        family,
      },
    }), [family]);
  const { data, update } = useAxiosRequest(config);
};

```

**Comment by londonbarrett** [comment]
It works! Thanks a lot :)
